### ISSUE TITLE
Feature request: LaTeX equation rendering

### ISSUE THREAD

**Issue by zeusttu** [yaniswang/markdownReader#10]
Currently, if I include a LaTeX equation in my markdown, it is just rendered as plain text. I believe that most flavours of Markdown actually support LaTeX equations by default and it would be great to have this feature in this Markdown reader as well.

**Comment by jovo** [comment]
+1!

**Comment by yaniswang** [comment]
https://chrome.google.com/webstore/detail/markdown-reader/gpoigdifkoadgajcincpilkjmejcaanc
Done!
