### ISSUE TITLE
GitHub-Flavored Markdown

### ISSUE THREAD

**Issue by chharvey** [yaniswang/markdownReader#11]
As per [GitHub-Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/):

- ~~Strikethrough~~ with surrounding `~~`
- Autolinking (no need for the `[]()` syntax when link text is a url): https://google.com
- Tables (see below)
- Syntax highlighting for code blocks (see below)

```
th1 | th2
--- | ---
td1 | td2
td3 | td4
```
th1 | th2
--- | ---
td1 | td2
td3 | td4
```html
<this is="an">html code block</this>
```
```css
.this > .is a {
  css: 'code' block;
}
```
```js
function js() {
  this.is = 'a js';
  var code = 'block';
}
```

**Comment by yaniswang** [comment]
https://chrome.google.com/webstore/detail/gpoigdifkoadgajcincpilkjmejcaanc/publish-delayed?utm_source=chrome-ntp-icon

Now supported.

**Comment by philsown** [comment]
Above Chrome Store link is dead. Is this no longer supported?

**Comment by philsown** [comment]
Thanks. That'z the one I had installed. I uninstalled & reinstalled, however, the "options" menu is grayed out. Is that where one selects GFM? How do I access this menu? Thanks!

**Comment by MattKleinsmith** [comment]
Overall GitHub-Flavored Markdown isn't an option (see https://github.com/yaniswang/markdownReader/issues/26). Those who want it will have to add it (i.e. via a pull request).
