### ISSUE TITLE
Bad-formatted list item notes

### ISSUE THREAD

**Issue by timlegrand** [yaniswang/markdownReader#12]
When righting notes under unumbered list items, the first one is rendered correctly but not the others.

This simple test case should reproduce the issue:

    Here is the bug :

    * the note below this item is OK
	    > it is well located and formatted
    * but not the following one
	    > it's printed at the end of the item
    * nor this one
	    > omg please do something

![capture](https://cloud.githubusercontent.com/assets/5445110/7314404/84ae326a-ea64-11e4-9aaf-f923fd33cd3f.PNG)

**Comment by yaniswang** [comment]
https://chrome.google.com/webstore/detail/markdown-reader/gpoigdifkoadgajcincpilkjmejcaanc
Done!
