### ISSUE TITLE
KaTeX is outdated

### ISSUE THREAD

**Issue by suluke** [yaniswang/markdownReader#18]
Hi!
I am trying to use matrices in my markdown with your plugin. This functionality was added to KaTeX back in June of 2015 ([see this issue](https://github.com/Khan/KaTeX/issues/43)) with version 0.4.0. The commit in your repo that added katex.min.js was in August 2015, so in theory it's possible that the version in markdownReader already supports matrices. At least I'm unable to get it to work...
Still, the KaTeX version in the repo is at least one and a half years old, so I would be nice if you could upgrade. Maybe you could also document the KaTeX version used by your browser extension.
Overall, I really appreciate markdownReader.

I can make a pull request with an updated KaTeX version if you'd like me to and if you think that nothing will break :)

**Comment by yaniswang** [comment]
Done!

New version is published.
