### ISSUE TITLE
Variables defined with commas

### ISSUE THREAD

**Issue by johncja** [yaniswang/markdownReader#19]
Hi! Thank you very much for markdownReader, it's really the best markdown viewer for Chrome.

I'm novice in JS and I'm trying to better understand your code. In `markdownreader.js` you sometimes declare variables using comma:

```
// lines 97-98:
var level = 0,
    lastLevel = 1;

// lines 157-158:
var fileurl = location.href,
    bLocalFile = /^file:\/\//i.test(fileurl);
```

instead of more traditional:

```
// lines 97-98:
var level = 0;
var lastLevel = 1;

// lines 157-158:
var fileurl = location.href;
var bLocalFile = /^file:\/\//i.test(fileurl);
```

Is there any reason why you do it this way?

I'm asking just for my self-education. Thanks :-)

**Comment by yaniswang** [comment]
The code is very older.

I like declare variables using no comma now.
