### ISSUE TITLE
inline math is in fact display math

### ISSUE THREAD

**Issue by hjy1210** [yaniswang/markdownReader#21]
1. What you call inline math. ordinary we call display math. 
2. Your demo matrix seems not diaplay correctly, in my chrome browser, only show one line.
3. Need feature: really in-line math such as $x^2$.

**Comment by yaniswang** [comment]
Can you show me url info about the inline math?
I am not very familiar with it.

**Comment by hjy1210** [comment]
Sorry, about inline math, it is my misunderstanding.

But matrix is not correctly displayed. See
<img width="369" alt="matrix" src="https://cloud.githubusercontent.com/assets/7498709/24396226/02f81618-13d5-11e7-905a-4899b0f4b141.png">

**Comment by yaniswang** [comment]
![image](https://cloud.githubusercontent.com/assets/970390/24398437/0005cd72-13dc-11e7-8dfb-d73e2455cc53.png)
