### ISSUE TITLE
Bug?: Options menu item disabled

### ISSUE THREAD

**Issue by MattKleinsmith** [yaniswang/markdownReader#26]
![screenshot from 2017-10-30 23-36-16](https://user-images.githubusercontent.com/8968171/32210505-25a666ba-bdcb-11e7-9edc-e6763d88d1df.png)

The options menu item is grayed out. I discovered this while trying to change the markdown style to the github flavored style mentioned in this issue: https://github.com/yaniswang/markdownReader/issues/11

**Comment by yaniswang** [comment]
This extension has no options menu

**Comment by MattKleinsmith** [comment]
@yaniswang 

My mistake. How can I enable the github style of markdown?

**Comment by yaniswang** [comment]
You can push your pr code to this project.
