### ISSUE TITLE
feature request: easy toggle-button in URL when extension is active

### ISSUE THREAD

**Issue by jzacsh** [yaniswang/markdownReader#9]
ie: it would be nice to be able to easily toggle the extension on and off when one wants to see the raw content _(without having to visit chrome://extensions, find the extension, untick "enable")_

eg: [JSON Formatter](https://github.com/callumlocke/json-formatter) chrome extension does this buttons at the top-right that are "raw" and "parsed" - even better would be if it was up in the URL bar so as not to be confused with the converted content.

**Comment by yaniswang** [comment]
Done!
Double click toogle raw content.

https://chrome.google.com/webstore/detail/markdown-reader/gpoigdifkoadgajcincpilkjmejcaanc
